### ISSUE TITLE
Only supports converting files up to 64K in size

### ISSUE THREAD

**Issue by God-damnit-all** [algonzalez/md-to-html#7]
Why is this limitation here? I had a [74KB markdown file](https://github.com/end2endzone/ShellAnything/blob/master/UserManual.md) I wanted to convert. I went ahead and just changed it in the source code, and it seemed to work fine.

**Comment by algonzalez** [comment]
The entire file is read in and processed, so I put this artificial limit in while I tested `Markdig`.

I meant to go back and up it to to 64Meg as well as add an option for `--no-size-check`. I'll get that in soon.

**Comment by algonzalez** [comment]
Since this is a command line tool, I've removed the arbitrary limit on the size of the file to be processed.
